version: "3"

services:
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command:
      ["uvicorn", "controller:app", "--host", "0.0.0.0", "--port", "3001"]

  proxy:
    container_name: proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email example@example.com -d example.com --agree-tos
